/** Warm torchlight in a deep twilight dungeon — gold wireframes with soft glow. */
export const emberglowTheme = {
  id: 'emberglow',
  name: 'Emberglow',
  description: 'Twilight depths, amber torchlight, and soft golden glow.',
  bodyClass: 'theme-emberglow',
  renderer: {
    creatureDepth: false,
    lineCap: 'round',
    viewportBg: '#060310',
    viewportBgInverted: '#f0e8f8',
    viewportGradient: {
      top: '#1a1038',
      bottom: '#04020c',
    },
    vignette: 0.42,
    glow: {
      blur: 10,
      color: 'rgba(255, 175, 95, 0.55)',
    },
    strokeLight: '#f5d9a8',
    strokeDark: '#2a1838',
    strokeCreature: '#ffb89a',
    strokeCeiling: '#a894d8',
    strokeObject: '#ffe08a',
    wallLineNear: 1.65,
    wallLineFar: 1.05,
    creatureLineNear: 1.9,
    creatureLineMid: 1.4,
    creatureLineFar: 1.05,
    creatureHighlight: true,
    minimap: {
      void: '#0a0614',
      floor: '#1e2848',
      wall: '#c9a86c',
      door: '#e8c878',
      player: '#ff6b5a',
      playerStroke: '#ffe8d0',
      label: '#d4c4f0',
      creatureStroke: '#1a1028',
    },
    heart: {
      healthy: '#e85d6a',
      low: '#b83050',
    },
  },
  css: {
    '--bg': '#0c0818',
    '--fg': '#e8ddf5',
    '--accent': '#e8b86d',
    '--panel': '#14102a',
    '--border': '#3d2f5c',
  },
};