/** Rotting flesh and bone — same wireframe silhouettes with scary textured fills. */
export const gravefleshTheme = {
  id: 'graveflesh',
  name: 'Graveflesh',
  description: 'Sickly flesh, dried blood, and bone under the same wireframe horrors.',
  bodyClass: 'theme-graveflesh',
  renderer: {
    creatureDepth: false,
    creatureTexture: true,
    lineCap: 'round',
    viewportBg: '#080604',
    viewportBgInverted: '#e8ddd0',
    viewportGradient: {
      top: '#1a100c',
      bottom: '#040302',
    },
    vignette: 0.55,
    strokeLight: '#c8b8a0',
    strokeDark: '#1a1008',
    strokeCreature: '#e8c8a8',
    strokeCeiling: '#6a5848',
    strokeObject: '#d8b878',
    wallLineNear: 1.5,
    wallLineFar: 1,
    creatureLineNear: 1.85,
    creatureLineMid: 1.35,
    creatureLineFar: 1,
    creatureHighlight: true,
    minimap: {
      void: '#0c0806',
      floor: '#2a2018',
      wall: '#8a7060',
      door: '#a87848',
      player: '#c84030',
      playerStroke: '#f0d8c0',
      label: '#c8b0a0',
      creatureStroke: '#1a1008',
    },
    heart: {
      healthy: '#8a3028',
      low: '#5a1818',
    },
  },
  css: {
    '--bg': '#0c0806',
    '--fg': '#d8c8b8',
    '--accent': '#a85840',
    '--panel': '#14100c',
    '--border': '#3a2820',
  },
};