/** Grok-imagined horror sprites — full photorealistic creatures on transparent backgrounds. */
export const nightmareTheme = {
  id: 'nightmare',
  name: 'Nightmare',
  description: 'Grok-imagined photorealistic horrors — creatures and dungeon walls.',
  bodyClass: 'theme-nightmare',
  renderer: {
    creatureDepth: false,
    creatureTexture: true,
    creatureSpriteSource: 'nightmare',
    wallTextureSource: 'nightmare',
    lineCap: 'round',
    viewportBg: '#050308',
    viewportBgInverted: '#e0d8e8',
    viewportGradient: {
      top: '#120818',
      bottom: '#020104',
    },
    vignette: 0.58,
    strokeLight: '#8a8a94',
    strokeDark: '#0c0c0e',
    strokeCreature: '#e8c0f0',
    strokeCeiling: '#3a3a42',
    strokeObject: '#9a9aa4',
    wallLineNear: 1.5,
    wallLineFar: 1,
    doorAccent: '#6a6a74',
    doorGlow: 'rgba(90, 90, 100, 0.35)',
    creatureLineNear: 1.85,
    creatureLineMid: 1.35,
    creatureLineFar: 1,
    creatureHighlight: true,
    minimap: {
      void: '#08080a',
      floor: '#1a1a1e',
      wall: '#4a4a52',
      door: '#5a5a64',
      player: '#d040a0',
      playerStroke: '#f0d0f8',
      label: '#c0a8d0',
      creatureStroke: '#100818',
    },
    heart: {
      healthy: '#9030a0',
      low: '#601858',
    },
  },
  css: {
    '--bg': '#08040c',
    '--fg': '#d8c8e8',
    '--accent': '#a050c0',
    '--panel': '#100818',
    '--border': '#382848',
  },
};